### ISSUE TITLE
Option to switch to a dark icon

### ISSUE THREAD

**Issue by NIXOYE** [uuttff8/Lemmy-iOS#10]
Itd be nice to have the option to change the icon to have a black background.

great work on the app btw!!

**Comment by uuttff8** [comment]
<img width="86" alt="Screenshot 2021-01-28 at 12 07 59 AM" src="https://user-images.githubusercontent.com/40335671/106054487-27767880-60fd-11eb-88c9-5743bdf902e7.png">

@NIXOYE  is that good looking black background icon ?

**Comment by NIXOYE** [comment]
yes :)

**Comment by uuttff8** [comment]
@NIXOYE Starting  from [this](https://github.com/uuttff8/Lemmy-iOS/commit/d39520a339ad2c062201e1d09ffe787904cb2d40) commit you can change background in App Info (settings) screen
