### ISSUE TITLE
App hangs after several minutes of use

### ISSUE THREAD

**Issue by kethle** [uuttff8/Lemmy-iOS#13]
After the update to 1.1.12, the app is very fast upon opening and then becomes unable to fetch new data after several minutes. 

When the app is closed and reopened, it works as expected until it times out again after a couple minutes. 

This is similar to an issue I have on the web app where it hangs and the page needs to be reloaded. In the webapp, it has error messages that it cannot connect to websockets. This was somewhat alleviated after they bumped the websocket timeout around v0.6 but it still remained an issue. 

Here is a sample ping on lemmy.ml

iPhone $ ping lemmy.ml 
PING lemmy.ml (5.196.14.162): 56 data bytes
64 bytes from 5.196.14.162: icmp_seq=0 ttl=48 time=335.611 ms
64 bytes from 5.196.14.162: icmp_seq=1 ttl=48 time=210.058 ms
64 bytes from 5.196.14.162: icmp_seq=2 ttl=48 time=221.463 ms
64 bytes from 5.196.14.162: icmp_seq=3 ttl=48 time=228.099 ms
64 bytes from 5.196.14.162: icmp_seq=4 ttl=48 time=226.811 ms
64 bytes from 5.196.14.162: icmp_seq=5 ttl=48 time=213.059 ms
64 bytes from 5.196.14.162: icmp_seq=6 ttl=48 time=218.171 ms

If you want any additional information, please let me know here or on the lemmy community as I am not often logged in here.

**Comment by uuttff8** [comment]
In my experience, after several minutes on new request app should reconnect to a websocket, isn't it?

**Comment by uuttff8** [comment]
Verified. I will think about fix.

**Comment by uuttff8** [comment]
should be fixed in https://github.com/uuttff8/Lemmy-iOS/commit/33d783676a209ec922ff6158a9768eb520416e9e

**Comment by kethle** [comment]
Indeed. Thank you!
